spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_info?serverTimezone=GMT%2B8&useSSL=false&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  aop:
    proxy-target-class: true
    auto: true
  redis:
    port: 6379
    host: localhost
    timeout: 10
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 100MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
mybatis-plus:
  mapper-locations: classpath:mapping/*.xml
  type-enums-package: com.yhdemo.demo.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: true
uploadfile:
  max-error-file: 100
  max-load-data: 50