spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_info?serverTimezone=GMT%2B8&useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  aop:
    proxy-target-class: true
    auto: true
mybatis-plus:
  mapper-locations: classpath:mapping/*.xml
  type-enums-package: com.yhdemo.demo.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl